### ISSUE TITLE
[Bug] NeoStore 1.0.4 Crashes Constantly on Nothing Phone

### ISSUE THREAD

**Issue by tdadvocate** [NeoApplications/Neo-Store#641]
**Describe the bug**
Application keeps crashing randomly every so many seconds upon launch.

**To Reproduce**
Unable to produce in any specific manner. Seems to randomly happen withing 5-60 seconds of opening the app. 

**Expected behavior**
Stay open to actually use it.

**Screenshots**
Not possible. 

**Relevant information:**

- Device: Nothing Phone (1)
- Android Version: 14
- ROM: NothingOS 2.5.6
- App's Version: 1.0.4
- Disabled battery optimization for Neo Store?: Yrs
- What is your selected installer?

-----------------------------

**Additional Notes**
This is seemingly not an issue on my Samsung Galaxy Fold 4 running OneUI 6.1 (Android 14).

**Comment by machiav3lli** [comment]
What repositories do you have active?

**Comment by tdadvocate** [comment]
> What repositories do you have active?

Just the default 3 (F-Droid, F-Droid Archive, and IzzyOnDroid). Though I've tried adding and removing with no success. It also won't let me remove any of the default 3. Every time I do, it either crashes or adds them back and then crashes.

**Comment by machiav3lli** [comment]
I can't reproduce it no matter what combinations I used, but had two similar reports in the community, so it's there but another one of those (for now) inexplainable edge cases.

**Comment by frasty** [comment]
Same here. Neo store 1.0.3+ crashes within approximately 60 seconds. It doesn't crash if you are in the settings menu, though. 

Realme 7 pro
Android 12

**Comment by elhennig** [comment]
For me it helped to clean the app cache, no more crashes afterwards

**Comment by frasty** [comment]
> For me it helped to clean the app cache, no more crashes afterwards

Unfortunately it didn't help on my device. 

Stack trace of the crash: 

```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 18053
java.lang.OutOfMemoryError: Failed to allocate a 2512 byte allocation with 1045536 free bytes and 1021KB until OOM, target footprint 134217728, growth limit 134217728; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:94)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:113)
	at androidx.core.os.HandlerCompat.toReleases(SourceFile:10)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl$getFlow$1.call(SourceFile:65)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a045a1c, androidx.compose.runtime.BroadcastFrameClock@4f71625, StandaloneCoroutine{Cancelling}@b91e3fa, AndroidUiDispatcher@df06dab]
```

**Comment by DawnVespero** [comment]
I've been having this issue too. Running v1.0.5 on a rooted Nothing Phone 2a. It seems to have started with the 1.0.5. update, but I have also had this problem on and off with some previous app versions. Clearing the app cache seems to have solved the issue for now. However, since I am using the root installer, I noticed that **the crashes always seem to occur when Neo Store requests SU permissions to update an app.** So it seems to me that this issue is related to the install process.

**It also seems to only occur with certain updates.** I recently installed FairEmail through Neo Store, but updating to version 1.2215 reliably crashed the app on install. Turning off automatic updates for that app fixed crashes on starting up Neo Store.

Hope that observation can help in clearing up this issue.

**Comment by LtqxWYEG** [comment]
Same problem here. Can't download and install or update one app before it crashes. Regardless of which app it is.
I also have stack traces for you:  
```errors
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 29572
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2336872 free bytes and 2282KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.String.fastSubstring(Native Method)
	at java.lang.String.substring(String.java:2069)
	at androidx.room.RoomOpenHelper.consumeKeyString(SourceFile:193)
	at androidx.room.RoomOpenHelper.consumeString(SourceFile:12)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(SourceFile:14)
	at kotlinx.serialization.internal.StringSerializer.deserialize(SourceFile:6)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:284)
	at kotlin.ranges.RangesKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:52)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(SourceFile:8)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:35)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:5)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:284)
	at kotlin.ranges.RangesKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:52)
	at com.machiav3lli.fdroid.database.entity.Release$$serializer.deserialize(SourceFile:95)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(SourceFile:284)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:30)
	at androidx.core.os.HandlerCompat.toReleases(SourceFile:85)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl$getFlow$1.call(SourceFile:65)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a88fb0e, androidx.compose.runtime.BroadcastFrameClock@3a5592f, StandaloneCoroutine{Cancelling}@7ed7b3c, AndroidUiDispatcher@811f0c5]


FATAL EXCEPTION: DefaultDispatcher-worker-18
Process: com.machiav3lli.fdroid, PID: 26917
java.lang.OutOfMemoryError: Failed to allocate a 528 byte allocation with 351960 free bytes and 343KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.io.ObjectOutputStream$BlockDataOutputStream.<init>(ObjectOutputStream.java:1810)
	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:248)
	at androidx.work.Data.toByteArrayInternal(SourceFile:13)
	at androidx.work.impl.model.WorkTagDao_Impl$1.bind(SourceFile:282)
	at androidx.room.EntityInsertionAdapter.insert(SourceFile:1)
	at androidx.work.impl.utils.WorkProgressUpdater$1.run(SourceFile:187)
	at androidx.work.Worker$2.run(SourceFile:280)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7cc6cfd, Dispatchers.IO]


FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 4670
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2539024 free bytes and 2479KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at androidx.core.os.HandlerCompat.toScreenshots(SourceFile:50)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl$getFlow$1.call(SourceFile:75)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@5e887a8, androidx.compose.runtime.BroadcastFrameClock@14722c1, StandaloneCoroutine{Cancelling}@a26ca66, AndroidUiDispatcher@51371a7]


FATAL EXCEPTION: DefaultDispatcher-worker-23
Process: com.machiav3lli.fdroid, PID: 22470
java.lang.OutOfMemoryError: Failed to allocate a 2672 byte allocation with 1738272 free bytes and 1697KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1973)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1855)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1245)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at androidx.work.Data.toByteArrayInternal(SourceFile:60)
	at androidx.work.Data$Builder.build(Unknown Source:7)
	at com.machiav3lli.fdroid.service.worker.DownloadWorker.setProgressAsync(SourceFile:108)
	at com.machiav3lli.fdroid.service.worker.DownloadWorker$handleDownload$2$callback$1.invokeSuspend(SourceFile:221)
	at com.machiav3lli.fdroid.service.worker.DownloadWorker$handleDownload$2$callback$1.invoke(SourceFile:32)
	at com.machiav3lli.fdroid.network.Downloader$dmDownload$2$1.invokeSuspend(SourceFile:52)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eeb6c03, Dispatchers.IO]
FATAL EXCEPTION: DefaultDispatcher-worker-70


FATAL EXCEPTION: FinalizerWatchdogDaemon
Process: com.machiav3lli.fdroid, PID: 11226
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.System.log(Native Method)
	at java.lang.System.logE(System.java:1734)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:294)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:920)
FATAL EXCEPTION: DefaultDispatcher-worker-71


FATAL EXCEPTION: DefaultDispatcher-worker-44
Process: com.machiav3lli.fdroid, PID: 8380
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2403840 free bytes and 2347KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at com.machiav3lli.fdroid.network.Downloader$dmDownload$2$1.invokeSuspend(SourceFile:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1144678, Dispatchers.IO]
FATAL EXCEPTION: DefaultDispatcher-worker-48


FATAL EXCEPTION: DefaultDispatcher-worker-68
Process: com.machiav3lli.fdroid, PID: 6006
java.lang.NoClassDefFoundError: kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt
	at kotlinx.coroutines.internal.AtomicKt.handleUncaughtCoroutineException(SourceFile:1)
	at kotlinx.coroutines.JobKt.handleCoroutineException(SourceFile:17)
	at androidx.work.Worker$2.run(SourceFile:34)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 1874936 free bytes and 1830KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.jar.Attributes.<init>(Attributes.java:74)
	at java.util.jar.Manifest.read(Manifest.java:248)
	at java.util.jar.Manifest.<init>(Manifest.java:69)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:202)
	at java.util.jar.JarFile.getManifest(JarFile.java:183)
	at java.util.jar.JarFile.maybeInstantiateVerifier(JarFile.java:354)
	at java.util.jar.JarFile.getInputStream(JarFile.java:455)
	at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
	at java.net.URL.openStream(URL.java:1072)
	at java.util.ServiceLoader.parse(ServiceLoader.java:305)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:183)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:358)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:402)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:488)
	at kotlin.sequences.SequencesKt.toList(SourceFile:5)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt.<clinit>(Unknown Source:18)
	at kotlinx.coroutines.internal.AtomicKt.handleUncaughtCoroutineException(SourceFile:1)
	at kotlinx.coroutines.JobKt.handleCoroutineException(SourceFile:17)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Unknown Source:2)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(SourceFile:105)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(SourceFile:221)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(SourceFile:5)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	... 2 more
FATAL EXCEPTION: DefaultDispatcher-worker-58


FATAL EXCEPTION: DefaultDispatcher-worker-36
Process: com.machiav3lli.fdroid, PID: 22035
java.lang.NoClassDefFoundError: kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt
	at kotlinx.coroutines.internal.AtomicKt.handleUncaughtCoroutineException(SourceFile:1)
	at kotlinx.coroutines.JobKt.handleCoroutineException(SourceFile:17)
	at androidx.work.Worker$2.run(SourceFile:34)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 372952 free bytes and 364KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:628)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.jar.Attributes.put(Attributes.java:148)
	at java.util.jar.Attributes.putValue(Attributes.java:168)
	at java.util.jar.Attributes.read(Attributes.java:421)
	at java.util.jar.Manifest.read(Manifest.java:251)
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:281)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
	at java.util.jar.JarVerifier.update(JarVerifier.java:229)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
	at java.util.jar.JarFile.getInputStream(JarFile.java:460)
	at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
	at java.net.URL.openStream(URL.java:1072)
	at java.util.ServiceLoader.parse(ServiceLoader.java:305)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:183)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:358)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:402)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:488)
	at kotlin.sequences.SequencesKt.toList(SourceFile:5)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt.<clinit>(Unknown Source:18)
	at kotlinx.coroutines.internal.AtomicKt.handleUncaughtCoroutineException(SourceFile:1)
	at kotlinx.coroutines.JobKt.handleCoroutineException(SourceFile:17)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Unknown Source:2)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(SourceFile:105)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(SourceFile:221)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(SourceFile:5)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	... 2 more
FATAL EXCEPTION: DefaultDispatcher-worker-38


FATAL EXCEPTION: WM.task-4
Process: com.machiav3lli.fdroid, PID: 32352
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1843448 free bytes and 1800KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1882)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2063)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
FATAL EXCEPTION: FinalizerWatchdogDaemon


FATAL EXCEPTION: DefaultDispatcher-worker-9
Process: com.machiav3lli.fdroid, PID: 8987
java.lang.SecurityException: Caller has no access to session 1262966963
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageInstaller$Stub$Proxy.openSession(IPackageInstaller.java:623)
	at android.content.pm.PackageInstaller.openSession(PackageInstaller.java:467)
	at com.machiav3lli.fdroid.installer.SessionInstaller.install(SourceFile:152)
	at com.machiav3lli.fdroid.service.worker.InstallWorker$doWork$installer$1.invokeSuspend(Unknown Source:40)
	at com.machiav3lli.fdroid.service.worker.InstallWorker$doWork$installer$1.invoke(SourceFile:20)
	at com.machiav3lli.fdroid.service.worker.InstallWorker$doWork$3.invokeSuspend(Unknown Source:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@856d568, Dispatchers.IO]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.openSessionInternal(PackageInstallerService.java:916)
	at com.android.server.pm.PackageInstallerService.openSession(PackageInstallerService.java:906)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:273)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
```
Etc, etc, pp and so forth... I can give you 40 more traces and if that's not enough, create an extra 40 for you within 10 minutes if you need.  
I can barely use the app, actually. :(

Kind regards, please fix, bye bye, thanks :)

**Comment by LtqxWYEG** [comment]
Something else came up while I was lazily looking at a logcat app. Maybe it is somehow related or at least you have an explanation for me:
![Screenshot_20240820-180922_Total Commander](https://github.com/user-attachments/assets/c10c4197-0411-4d5c-8a0c-f7760b46d808)
These APKs are all recently manually downloaded/updated apps. There is, afaik, no reason to expect FairEmail in there. It hasn't been updated for quite a while.

Why may it be related? Well maybe it would have crashed would I have had the app open at the time. (Not touched it for at least 6 hours, at most 24)

**Comment by PowerUser64** [comment]
I'd be willing to test debug builds and share logs if it would help solve this!

I have this happening to me on my Pixel 3a (Android 14/LineageOS), add will as my Kindle Fire (Android 7.1/LineageOS). Neostore has become pretty much unusable on these devices and I've had to reinstall basic f-droid to update anything.

**Comment by LtqxWYEG** [comment]
I somewhat fixed it by reinstalling the app and limiting the selected repositories to the default.  
Now crashes are less frequent.

Maybe there is a problem with files persisting throughout the several updates. I had a "old" installation of it. However, cleaner have regularly deleted the cache - but not storage - so it's not a cache problem.

**Comment by PowerUser64** [comment]
I think that release [v1.1.0](https://github.com/NeoApplications/Neo-Store/releases/tag/1.1.0) might have solved this issue. All the releases since then have been much better.
